dojoengine/book

src/framework/cairo/commands.md
src/framework/cairo/components.md
src/framework/cairo/entities.md
src/framework/cairo/systems.md

updated for macros and IWorldDispatcher

---

book.toml
src/README.md
src/theory/autonomous-worlds.md

- updated readme
- added Tarrence's video
- added some thinkboi stuff

Sylve update

---

src/cairo/hello-dojo.md

use correct command output

---

src/toolchain/torii/reference.md

Updating torii's reference, using katana doc as template

Update torii ref

---

src/README.md

https://book.dojoengine.org/
https://book.dojoengine.org/misc/contributors.html!
\_____ error code: 404 (not found)

Fix the broken link

---

src/tutorial/onchain-chess/3-legal.md

https://book.dojoengine.org/tutorial/onchain-chess/3-legal.html
https://github.com/rkdud007/chess-dojo/blob/tutoralv2/src/systems/move.cairo
\_____ error code: 404 (not found)

docs: Delete the expired answer links

---

LANGUAGES
po/ja.po
theme/index.hbs

Hi forks!
I just translated all the content into Japanese.
Please it my implementation.
I was inspired by my friend @cryptonerdcn yesterday
This is the beginning, I want to contribute more🌏⛩️

[i18n] Add Japanese translation for Dojo book.

---

src/cairo/testing.md

I've updated the testing doc to 0.3.0 format and made a PR to both the main branch and 0.3.0 as per request. Kindly review this and let me know what you think incase there are changes that needs to be made

testing updated to 0.3.0 format

---

src/cairo/hello-dojo.md
src/toolchain/torii/graphql.md

- Update hello-dojo.md
- Update graphql.md

Update Hello-dojo and graphql to v0.3.0-rc8

---

src/SUMMARY.md
src/cairo/components.md
src/cairo/hello-dojo.md
src/toolchain/torii/graphql.md

Update hello-dojo tutorial with dojo-starter v0.3.0
Resolves #84

Update hello-dojo tutorial 

---

src/cairo/hello-dojo.md

Update hello-dojo according to updated dojo-starter

Update hello-dojo 

---

0.2.0/src/cairo/hello-dojo.md
0.2.0/src/cairo/modules.md
0.2.0/src/cairo/systems.md
0.2.0/src/cairo/testing.md
0.2.0/src/client/npm/core.md
0.2.0/src/deployment/locally.md
0.2.0/src/deployment/remote.md

Hello,
I fixed some minor typos in several files in the docs.
hope it helps
Br,
Tudor.

fix: minor typos in the documentation

---

src/README.md
src/cairo/entities.md
src/cairo/hello-dojo.md
src/cairo/overview.md
src/cairo/testing.md
src/theory/cairo.md
src/theory/what-is-dojo.md
src/toolchain/katana/overview.md

- Update outdated remaining key works, terms, and code form version 0.2
- Fix broken links
ToDo: Update Systems section

Update book content

---

src/SUMMARY.md
src/toolchain/sozo/common-options/offline.md
src/toolchain/sozo/common-options/profile.md
src/toolchain/sozo/project-commands/migrate.md
src/toolchain/sozo/reference.md

add docs for sozo common options (profile/offline)
fix slot>reference>deployments

add docs for sozo common options (profile/offline)

---

main.py
readme.md
requirements.txt

add lang script

---

src/cairo/events.md
src/cairo/migration/0.3.0.md

fix events content

---

src/cairo/models.md

fix models content

---

src/cairo/hello-dojo.md
src/cairo/systems.md

Resolves #125 
@glihm WDYT about? I think we still have to work on this.

Update systems concept

---

src/cairo/hello-dojo.md
src/toolchain/torii/graphql.md

remove model_names from Graphql query

---

src/toolchain/sozo/project-commands/migrate.md
src/toolchain/torii/overview.md

Some broken links referencing an other markdown document.

fix: broken links

---

src/cairo/config.md

Update Config file

---

src/cairo/hello-dojo.md
src/toolchain/torii/graphql.md

Update graphql and hello-dojo

---

docs/pages/cairo/commands.md
docs/pages/cairo/config.md
docs/pages/cairo/hello-dojo.md
docs/pages/community/get-started.md

Minor updates

---

docs/pages/cairo/commands.md
docs/pages/getting-started.md
docs/pages/toolchain/sozo/project-commands/init.md

Fix deadlink and minor clarification

---

readme.md

Inclusion of Setup Instructions for Vocs Dependencies and Execution.

Enhance Readme.md

---

vocs.config.ts

Dojo js was not accessible, thanks @gianalarcon. :pray:

fix: fix broken link for dojo.js

---

docs/pages/toolchain/sozo/world-commands/register.md

update sozo register command

---

docs/pages/cairo/hello-dojo.md

Closes #240 
In order to fully update this section. We also have to update the `dojo-starter` repo.
Related to this [PR](https://github.com/dojoengine/dojo-starter/pull/46)

Update Hello-dojo tutorial to dojo v0.6.0-alpha.7

---

docs/pages/cairo/testing.md
docs/pages/tutorial/katana-starkli-scarb/main.md
docs/pages/tutorial/onchain-chess/0-setup.md
docs/pages/tutorial/onchain-chess/2-move.md
docs/pages/tutorial/onchain-chess/3-test.md

Update contents to use assert! macro

Migrate to assert! macro

---

docs/pages/cairo/models.md

worked on the upgrading models and data migration

---

docs/pages/cairo/hello-dojo.md
docs/pages/cairo/models.md
docs/pages/cairo/overview.md
docs/pages/cairo/systems.md
docs/pages/getting-started/quick-start.md
docs/pages/theory/what-is-dojo.mdx
docs/pages/toolchain/katana/interact.md
docs/pages/tutorial/deploy-using-slot/main.md

- Remove `ContractState` usage
- Update `sozo init` command
- Remove mention of `alpha` versions

Remove ContractState usage

---

docs/pages/cairo/hello-dojo.md
docs/pages/client/sdk/unity/common-problems.md
docs/pages/client/sdk/unity/important-concepts.md
docs/pages/tutorial/onchain-chess/0-setup.md

- Update mentions of dojo `alpha` version to dojo `stable` version

Docs: Clean dojo alpha version

---

vocs.config.ts

fix: broken links in book

---

docs/pages/toolchain/slot/deployments-commands/deployments.md
docs/pages/tutorial/deploy-using-slot/main.md

updated the slot migrate instructions

doc: update slot migrate commands

---

docs/pages/toolchain/katana/genesis.md

chore: change classHash to class name

---

docs/pages/framework/authorization/index.mdx
docs/pages/framework/config.md

Add first config explain, will break down the items of the config into different pages.

fix: start config rework

---

docs/pages/toolchain/katana/cli/katana.md

ref https://github.com/dojoengine/dojo/pull/2663

Update Katana CLI arguments 

---

docs/pages/framework/index.mdx
docs/pages/framework/models/enum.md
docs/pages/framework/models/index.md
docs/pages/framework/models/introspect.md
docs/pages/framework/world/events.md
docs/pages/framework/world/index.md
docs/pages/framework/world/systems.md
docs/pages/tutorial/dojo-starter.mdx
docs/pages/welcome-1.mdx

This PR:
- fixes some typos,
- fixes some code indentation to avoid having to scroll horizontally to see the whole code snippet, when it's possible,
- updates some old contents.

fix some typos + old content + code identation

---

docs/pages/framework/world/metadata.md
docs/pages/toolchain/sozo/project-commands/migrate.mdx

Update the Metadata page according to https://github.com/dojoengine/dojo/pull/2691.

feat: update metadata page

---

docs/pages/tutorial/deploy-to-mainnet/main.md

feat: mainnet deployment tutorial notes.

---

docs/pages/framework/config.md

Added information about `build-external-contract`

---

docs/pages/toolchain/katana/cli/katana.md

I add the documentation about using the explorer flag.
PR for the feature here https://github.com/dojoengine/dojo/pull/2997

chore: update explorer documentation 
