src/framework/katana/overview.md
src/framework/sozo/overview.md
src/theory/cairo.md

This PR provide the following modifications:
- fix broken link to 'commands' in theory/cairo
- add missing #using-dojoup for reference to dojoup

Update internal links

---

src/deployment/locally.md

Small fix, following the deployment tutorial, I noticed that the links were broken

[Fix] 📁Deployment - Katana and Quick Start urls

---

src/cairo/commands.md
src/cairo/config.md
src/cairo/events.md
src/cairo/hello-dojo.md
src/cairo/models.md
src/cairo/testing.md

Fix some typos.
@ponderingdemocritus I've run prettier but there is a lot's of diff. Are you using a special script/tool for this?
We may include it (or something similar) and make a check in the CI. This could help to keep the markdown formatted, WDYT?

fix: typos

---

src/cairo/overview.md

Resolves #124 
@glihm I suggest to change it like this, WDYT?

fix content about dispatcher

---

src/cairo/systems.md

On Overview -> Systems page, It says that, All Starknet contracts are defined using the #[dojo::contract] decorator
In should instead be: All Starknet contracts are defined using the #[starknet::contract] decorator
#156

Fix Overview -> Systems page

---

src/tutorial/onchain-chess/0-setup.md

Fix Chess example hyperlink to origami repository. Currently its broken.

Fix chess example hyperlink

---

src/client/sdk/unity.md

The link with the ahref (dojo-starter-unity) was pointing to https://book.dojoengine.org/cairo/hello-dojo.html instead of the [Dojo Starter Unity Page] (https://github.com/dojoengine/dojo-starter-unity)

chore: update unity.md

---

src/toolchain/katana/reference.md

Since https://github.com/dojoengine/dojo/commit/431d015e3fc43a72f528fbeac741a098b667f7e7 load_state is not there anymore

Remove load_state from the katana reference

---

src/client/sdk/unity.md

As git clone git@github.com:dojoengine/dojo.c.git
cargo build --release 
Returns Error the following error:  git clone git@github.com:dojoengine/dojo.c.git
fatal: could not create work tree dir 'dojo.c': Permission denied
C:\Users>cargo build --release
'cargo' is not recognized as an internal or external command, operable program or batch file.
Changing the code to git clone https://github.com/dojoengine/dojo works

chore: git clone link updated

---

src/toolchain/sozo/world-commands/model.md

Update `sozo model `commands as they are outdated. The commands now look like this:
- `class-hash`: Get the class hash of a model
- `schema`: Retrieve the schema for a model
- `get`: Get the model value for an entity.
[Source code](https://github.com/dojoengine/dojo/blob/3bb35a6790de3eea83e5c728ed0de46523a3de10/crates/sozo/src/commands/model.rs#L18)

Update section Sozo model

---

docs/pages/tutorial/onchain-chess/0-setup.md

Fixing a typo in tutorial : onchain-chess
Changed models/player.cairo to models/game.cairo to accurately reflect the instructions for editing the game model file.
Updated models/player.cairo to models/piece.cairo to accurately reflect the instructions for editing the piece model file.

 fixing a typo in tutorial-onchain-chess

---

docs/pages/toolchain/sozo/project-commands/migrate.mdx

lambda-0x, here is the text mentioned in DM, please don't hesitate to take over on the details of that.
For now it's fine to have the manifests being detailed on the `sozo reference`, and we should think of a better place for them.
@gianalarcon @ponderingdemocritus any suggestion?

add overlay introduction text

---

docs/pages/toolchain/sozo/common-options/configurations.md
vocs.config.ts

This the issue https://github.com/dojoengine/book/issues/176
Sozo is being reworked to have these priorities:
- CLI arguments always takes precedence.
- Then the environment variables.
- Finally, anything found inside the scarb manifest.
We may add a section on that on the book once this PR is merged https://github.com/dojoengine/dojo/pull/1405 to bring better understanding for the user to the possibilities around configurations.

Add information about sozo arguments priorities #176

---

docs/pages/toolchain/sozo/project-commands/init.md

This PR updates the documentation on initializing a new dojo project using `sozo init`.

doc: sozo init doc

---

docs/pages/welcome-1.mdx

This PR updates the "Welcome to Dojo 1.0.0" page. It fixed the `emit_event` syntax and added the `use dojo::world::IWorldDispatcherTrait;` import so that the World API's methods can be found

fix: update welcome to dojo 1.0.0

---

docs/pages/quickstarts/react.mdx

The React quickstart guide is outdated and incomplete:
- still uses `--disable-fee` for `katana` which has been changed to `--dev.no-fee`
- does not tell user to run indexer
This PR fixes both issues.

fix: broken React quickstart guide

---

docs/pages/framework/testing-cheat-codes.md

This PR fixes a typo in the assert function within the set_caller_address example in the Dojo book.

fix: fix typo in the assert function in set_caller_address example

---

docs/pages/framework/models/index.md

This PR enhances the documentation by adding a clear explanation of why the Drop and Serde traits are mandatory.
This update encourages continuous learning for developers who are not yet fully familiar with Cairo, helping them better understand key concepts and lowering the entry barrier.
Feedback on the clarity and accuracy of the explanation is welcome.
Let me know if further adjustments are needed!

Improve Models Documentation: Explain why Drop and Serde Traits are mandatory

---

docs/pages/framework/models/upgrades.md
routes.ts

Related to https://github.com/dojoengine/dojo/pull/2925.

feat: add model upgrades page

---

docs/pages/framework/config.md
docs/pages/toolchain/sozo/calldata_format.md
docs/pages/toolchain/sozo/world-commands/call.mdx
docs/pages/toolchain/sozo/world-commands/execute.mdx
routes.ts

This PR adds:
- a dedicated page to describe the calldata format used by `sozo` and some configuration files,
- a description of the new `external_contracts` block in `dojo_<PROFILE>.toml` and added in this PR https://github.com/dojoengine/dojo/pull/2995.

Sozo: add calldata format page + external contracts configuration description

---

docs/pages/toolchain/saya/persistent.md

Related to https://github.com/dojoengine/dojo/pull/3158.

feat(katana): add fact registry arg for `init`
